version: '3.0'
volumes:
    server_volume:
    client_volume:
    worker_volume:
services:
    postgres:
        image: 'postgres:latest'
    redis:
        image: 'redis:latest'
    #api = server
    api:
        build:
            dockerfile: Dockerfile.dev
            context: ./server
        volumes:
            - server_volume:/app/node_modules
            - ./server:/app
        environment:
            - REDIS_HOST=redis
            - REDIS_PORT=6379 
            - PGUSER=postgres
            - PGHOST=postgres
            - PGDATABASE=postgres 
            - PGPASSWORD=postgres_password
            - PGPORT=5432
        depends_on:
            - postgres
    client:
        build:
            dockerfile: Dockerfile.dev
            context: ./client
        volumes:
            - client_volume:/app/node_modules
            - ./client:/app
    worker:
        build:
            dockerfile: Dockerfile.dev
            context: ./worker
        volumes:
            - worker_volume:/app/node_modules
            - ./worker:/app
        environment:
            - REDIS_HOST=redis
            - REDIS_PORT=6379
    nginx:
        restart: always
        build:
            dockerfile: Dockerfile.dev
            context: ./nginx
        ports:
            - '3050:80'

